import "@/app/globals.css";

import cx from "classnames";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cx(
          inter.className,
          "flex justify-center h-full w-full m-0 p-0 bg-[#d6d6d6]"
        )}
      >
        <div className="overflow-auto bg-[#f5f5f5] shadow-lg sm:h-screen sm:w-screen md:h-auto md:max-h-[800px] md:min-h-[800px] md:w-[768px]">
          <main>{children}</main>
        </div>
      </body>
    </html>
  );
}
