import "@/app/globals.css";

import cx from "classnames";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { Layout } from "@/app/_components/layouts";
import { UnauthorizedError } from "@/libs/error";
import { fetchNotificationClient } from "@/services/client/notificationFetch";
import { serverComponentAuthValidateAndReturnUid } from "@/services/server/auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  modal,
}: {
  children: React.ReactNode;
  modal: React.ReactNode;
}) {
  const userId = await serverComponentAuthValidateAndReturnUid();
  if (!userId) throw new UnauthorizedError();
  const userMessagePromise = fetchNotificationClient(userId);

  return (
    <html lang="en">
      <body
        className={cx(
          inter.className,
          "flex justify-center h-full w-full m-0 p-0 bg-[#d6d6d6]"
        )}
      >
        <Layout userMessagePromise={userMessagePromise}>{children}</Layout>
        {modal}
      </body>
    </html>
  );
}
