# ref : https://budiirawan.com/how-to-publish-storybook-github-pages/
name: Storybook
on:
  push:
    branches:
      - develop 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install and Build
        run: |
          npm ci
          npm run build-storybook
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4
        with:
          branch: gh-pages
          folder: storybook-static # output folder from `npm run build-storybook`